-- 29.school — Study Guides schema
--
-- Apply by pasting this entire file into the Supabase SQL Editor
-- (https://supabase.com/dashboard/project/_/sql) and running it.
-- Safe to re-run: every statement uses IF NOT EXISTS / OR REPLACE.

-- ---------- Tables ----------

create table if not exists public.classes (
  id          bigint generated by default as identity primary key,
  name        text not null,
  created_at  timestamptz not null default now()
);

create unique index if not exists classes_name_unique
  on public.classes (lower(name));

create table if not exists public.study_guides (
  id          bigint generated by default as identity primary key,
  class_id    bigint not null references public.classes(id) on delete cascade,
  title       text not null,
  type        text not null check (type in ('pdf', 'link')),
  url         text not null,
  created_at  timestamptz not null default now()
);

create index if not exists study_guides_class_id_idx
  on public.study_guides (class_id);

create index if not exists study_guides_created_at_idx
  on public.study_guides (created_at);

-- ---------- Row-Level Security ----------
-- The app uses the service-role key from a server-only context, which
-- bypasses RLS. RLS is still enabled here so the anon/public keys cannot
-- read or write directly even if they were ever exposed.

alter table public.classes      enable row level security;
alter table public.study_guides enable row level security;

-- ---------- Storage bucket for PDFs ----------
-- The app uploads PDFs to a public bucket named `study-guides`. Created
-- here for convenience; safe if it already exists.

insert into storage.buckets (id, name, public)
values ('study-guides', 'study-guides', true)
on conflict (id) do update set public = excluded.public;

-- ---------- PostgREST schema cache reload ----------
-- Tells PostgREST to refresh its cached schema so the new tables are
-- immediately usable from the REST API.

notify pgrst, 'reload schema';
